### ISSUE TITLE
Uncaught Error: Class 'Parse_This' not found when posting via Micropub

### ISSUE THREAD

**Issue by ngm** [dshanske/indieweb-post-kinds#244]
I'm getting the following error when trying to like a post via Micropub:

```
PHP Fatal error:  Uncaught Error: Class 'Parse_This' not found in /.../public_html/wp-content/plugins/indieweb-post-kinds/includes/class-kind-plugins.php:108
Stack trace:
#0 /.../public_html/wp-includes/class-wp-hook.php(286): Kind_Plugins::micropub_parse(Array)
#1 /.../public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)
#2 /.../public_html/wp-content/plugins/micropub/includes/class-micropub-endpoint.php(170): apply_filters('before_micropub', Array)
#3 /.../public_html/wp-content/plugins/micropub/includes/class-micropub-endpoint.php(222): Micropub_Endpoint::load_input(Object(WP_REST_Request))
#4 /.../public_html/wp-includes/rest-api/class-wp-rest-server.php(936): Micropub_Endpoint::post_handler(Object(WP_REST_Request))
#5 /.../public_html/wp-includes/rest-api/class-wp-rest-server.php(321): WP_REST_Server->dispatch(Object(WP_REST_Request))
#6 /.../publi in /.../public_html/wp-content/plugins/indieweb-post-kinds/includes/class-kind-plugins.php on line 108
```

The same error is occurring if I do the like from either Indigenous or Monocle.  If I do the like from within Wordpress, it works OK.  So seems it may be Micropub related?

Plugin versions:

indieweb-post-kinds: 3.1.7
micropub: 2.0.6

**Comment by dshanske** [comment]
I will take care of it quickly. It's in Post Kinds

**Comment by ngm** [comment]
Brilliant, thanks!  Updated and it's working again now.
