### ISSUE TITLE
Error with ownyourswarm's Import Past Checkin

### ISSUE THREAD

**Issue by chrisbergr** [dshanske/indieweb-post-kinds#353]
I got the following messages in my debug.log after using the manual import function of ownyourswarm.

```

[30-Apr-2023 23:17:10 UTC] Unknown cap: manage_options
[30-Apr-2023 23:17:10 UTC] Unknown cap: manage_options
[30-Apr-2023 23:17:10 UTC] Unknown cap: upload_files
[30-Apr-2023 23:17:10 UTC] Unknown cap: manage_options
[30-Apr-2023 23:17:10 UTC] Unknown cap: manage_options
[30-Apr-2023 23:17:10 UTC] Unknown cap: upload_files
[30-Apr-2023 23:17:10 UTC] Micropub Input: {"type":["h-entry"],"properties":{"published":["2023-04-28T14:29:32+02:00"],"syndication":["https:\/\/www.swarmapp.com\/user\/91657961\/checkin\/644bbc2c7c391c3fdd8d33c1"],"content":["Improvements from the last appointment"],"photo":["https:\/\/fastly.4sqi.net\/img\/general\/original\/91657961_cwSdaFv3w10p_VU6wewBtGz7aoW8M3LoMriSn8sCvlk.jpg","https:\/\/fastly.4sqi.net\/img\/general\/original\/91657961_viWftIo_Zbk4lw8JS5uWNXwUcrOnQWZRSjjwd2PI70c.jpg","https:\/\/fastly.4sqi.net\/img\/general\/original\/91657961_eEE0B-DNjCr6qnRP9_X8Z7pRyr4WCUedNHetme_DPXc.jpg","https:\/\/fastly.4sqi.net\/img\/general\/original\/91657961_vi4ACwGWxLCW5t4Q4mkLB6ntj6n6BQcW8GHeZwsT2M8.jpg","https:\/\/fastly.4sqi.net\/img\/general\/original\/91657961_5HUpiwqP_3S3nTsQjawqlObuwc7JDCYnYDTxvFHIToA.jpg"],"category":["checkin"],"checkin":[{"type":["h-card"],"properties":{"name":["K\u00fchn Und W\u00fcsthoff Zahnheilkunde"],"url":["https:\/\/foursquare.com\/v\/63b5985e047655037cd6b9d4","https:\/\/www.kuehn-wuesthoff.de"],"tel":["0621 653108"],"latitude":[49.519497],"longitude":[8.408262],"street-address":["Austra\u00dfe 4"],"locality":["Ludwigshafen am Rhein"],"region":["Rheinland-Pfalz"],"country-name":["Germany"],"postal-code":["67069"]},"value":"https:\/\/foursquare.com\/v\/63b5985e047655037cd6b9d4"}],"location":[{"type":["h-adr"],"properties":{"latitude":[49.519497],"longitude":[8.408262],"street-address":["Austra\u00dfe 4"],"locality":["Ludwigshafen am Rhein"],"region":["Rheinland-Pfalz"],"country-name":["Germany"],"postal-code":["67069"]}}]}}
[30-Apr-2023 23:17:10 UTC] wp_insert_post with args: {"timezone":"+02:00","post_date":"2023-04-28 14:29:32","post_date_gmt":"2023-04-28 12:29:32","post_category":[800],"tags_input":[],"post_content":"Improvements from the last appointment","post_type":"post","tax_input":null,"meta_input":{"micropub_auth_response":{"client_id":"https:\/\/ownyourswarm.p3k.io\/","client_name":"OwnYourSwarm","uuid":"98cbeb8d-1e2b-4881-a76b-58e4d2d77a1f"},"mf2_type":["h-entry"],"geo_timezone":"+02:00","mf2_syndication":["https:\/\/www.swarmapp.com\/user\/91657961\/checkin\/644bbc2c7c391c3fdd8d33c1"],"mf2_content":["Improvements from the last appointment"],"mf2_photo":["https:\/\/fastly.4sqi.net\/img\/general\/original\/91657961_cwSdaFv3w10p_VU6wewBtGz7aoW8M3LoMriSn8sCvlk.jpg","https:\/\/fastly.4sqi.net\/img\/general\/original\/91657961_viWftIo_Zbk4lw8JS5uWNXwUcrOnQWZRSjjwd2PI70c.jpg","https:\/\/fastly.4sqi.net\/img\/general\/original\/91657961_eEE0B-DNjCr6qnRP9_X8Z7pRyr4WCUedNHetme_DPXc.jpg","https:\/\/fastly.4sqi.net\/img\/general\/original\/91657961_vi4ACwGWxLCW5t4Q4mkLB6ntj6n6BQcW8GHeZwsT2M8.jpg","https:\/\/fastly.4sqi.net\/img\/general\/original\/91657961_5HUpiwqP_3S3nTsQjawqlObuwc7JDCYnYDTxvFHIToA.jpg"],"mf2_category":["checkin"],"mf2_checkin":{"type":["h-card"],"properties":{"name":["K\u00fchn Und W\u00fcsthoff Zahnheilkunde"],"url":["https:\/\/foursquare.com\/v\/63b5985e047655037cd6b9d4","https:\/\/www.kuehn-wuesthoff.de"],"tel":["0621 653108"],"latitude":[49.519497],"longitude":[8.408262],"street-address":["Austra\u00dfe 4"],"locality":["Ludwigshafen am Rhein"],"region":["Rheinland-Pfalz"],"country-name":["Germany"],"postal-code":["67069"]},"value":"https:\/\/foursquare.com\/v\/63b5985e047655037cd6b9d4"},"mf2_location":{"type":["h-adr"],"properties":{"latitude":[49.519497],"longitude":[8.408262],"street-address":["Austra\u00dfe 4"],"locality":["Ludwigshafen am Rhein"],"region":["Rheinland-Pfalz"],"country-name":["Germany"],"postal-code":["67069"]}},"geo_address":"Austra\u00dfe 4, Ludwigshafen am Rhein, Rheinland-Pfalz, 67069, Germany","geo_latitude":49.519497,"geo_longitude":8.408262},"post_author":1,"post_status":"publish"}
[30-Apr-2023 23:17:10 UTC] Unknown cap: read_private_posts

```

```
[30-Apr-2023 23:17:11 UTC] PHP Warning:  Undefined array key "ExifVersion" in /var/mysite/wp-content/plugins/simple-location/includes/class-sloc-media-metadata.php on line 59
[30-Apr-2023 23:17:11 UTC] Unknown cap: upload_files
[30-Apr-2023 23:17:11 UTC] PHP Warning:  Undefined array key "ExifVersion" in /var/mysite/wp-content/plugins/simple-location/includes/class-sloc-media-metadata.php on line 59
```
```

[30-Apr-2023 23:17:13 UTC] PHP Fatal error:  Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, null given in /var/mysite/wp-content/plugins/indieweb-post-kinds/includes/class-kind-media-metadata.php:274
Stack trace:
#0 /var/mysite/wp-content/plugins/indieweb-post-kinds/includes/class-kind-media-metadata.php(274): array_filter()
#1 /var/mysite/wp-includes/class-wp-hook.php(310): Kind_Media_Metadata::wp_generate_attachment_metadata()
#2 /var/mysite/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#3 /var/mysite/wp-admin/includes/image.php(658): apply_filters()
#4 /var/mysite/wp-content/plugins/micropub/includes/class-micropub-media.php(221): wp_generate_attachment_metadata()
#5 /var/mysite/wp-content/plugins/micropub/includes/class-micropub-media.php(454): Micropub_Media::insert_attachment()
#6 /var/mysite/wp-content/plugins/micropub/includes/class-micropub-endpoint.php(810): Micropub_Media::media_sideload_url()
#7 /var/mysite/wp-content/plugins/micropub/includes/class-micropub-endpoint.php(485): Micropub_Endpoint::default_file_handler()
#8 /var/mysite/wp-content/plugins/micropub/includes/class-micropub-endpoint.php(216): Micropub_Endpoint::create()
#9 /var/mysite/wp-includes/rest-api/class-wp-rest-server.php(1181): Micropub_Endpoint::post_handler()
#10 /var/mysite/wp-includes/rest-api/class-wp-rest-server.php(1028): WP_REST_Server->respond_to_request()
#11 /var/mysite/wp-includes/rest-api/class-wp-rest-server.php(442): WP_REST_Server->dispatch()
#12 /var/mysite/wp-includes/rest-api.php(410): WP_REST_Server->serve_request()
#13 /var/mysite/wp-includes/class-wp-hook.php(308): rest_api_loaded()
#14 /var/mysite/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#15 /var/mysite/wp-includes/plugin.php(565): WP_Hook->do_action()
#16 /var/mysite/wp-includes/class-wp.php(399): do_action_ref_array()
#17 /var/mysite/wp-includes/class-wp.php(780): WP->parse_request()
#18 /var/mysite/wp-includes/functions.php(1334): WP->main()
#19 /var/mysite/wp-blog-header.php(16): wp()
#20 /var/mysite/index.php(17): require('...')
#21 {main}
  thrown in /var/mysite/wp-content/plugins/indieweb-post-kinds/includes/class-kind-media-metadata.php on line 274

```

**Comment by dshanske** [comment]
Resolved.
